// Command contractgen generates TypeScript runtime validators from a
// versioned JSON Schema. The checked-in output is deterministic and --check
// turns schema/consumer drift into a CI failure.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
)

func main() {
	schemaPath := flag.String("schema", "api/view_contracts/k12-image-task.v1.schema.json", "input JSON Schema")
	outPath := flag.String("out", "../hexclaw-desktop/src/contracts/generated/k12-image-task.v1.ts", "generated TypeScript")
	check := flag.Bool("check", false, "fail if generated output differs")
	flag.Parse()

	raw, err := os.ReadFile(*schemaPath)
	if err != nil {
		fatal(err)
	}
	var schema any
	if err := json.Unmarshal(raw, &schema); err != nil {
		fatal(fmt.Errorf("decode schema: %w", err))
	}
	canonical, err := json.MarshalIndent(schema, "", "  ")
	if err != nil {
		fatal(err)
	}
	generated := render(canonical)
	if *check {
		current, readErr := os.ReadFile(*outPath)
		if readErr != nil || !bytes.Equal(current, generated) {
			fatal(fmt.Errorf("generated contract drift: run go run ./cmd/contractgen -schema %s -out %s", *schemaPath, *outPath))
		}
		return
	}
	if err := os.MkdirAll(filepath.Dir(*outPath), 0o755); err != nil {
		fatal(err)
	}
	if err := os.WriteFile(*outPath, generated, 0o644); err != nil {
		fatal(err)
	}
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "contractgen:", err)
	os.Exit(1)
}

func render(schema []byte) []byte {
	return []byte(`// Code generated by hexclaw/cmd/contractgen from k12-image-task.v1.schema.json. DO NOT EDIT.

export const K12_IMAGE_TASK_SCHEMA_VERSION = 'v1' as const
export const K12_IMAGE_TASK_SCHEMA = ` + string(schema) + ` as const

export interface K12ImageTaskDispatch {
  dispatch_id: string
  task_intent: string
  status: string
  failure_kind?: string
  progress: { operation: string; state: string }
  version: number
  [key: string]: unknown
}

export interface K12ImageTaskCreateResponse {
  created: boolean
  dispatch: K12ImageTaskDispatch & Record<string, unknown>
}
export interface K12ImageTaskDispatchResponse {
  dispatch: K12ImageTaskDispatch & Record<string, unknown>
}
export interface K12ImageTaskResultResponse extends Record<string, unknown> {
  failure_kind?: string
  result: Record<string, unknown>
}
export type K12ImageTaskProblemSourceAction = 'correct_text' | 'select_region' | 'retake' | 'skip' | 'resume'
export type K12ImageTaskProblemSourceStatus =
  (typeof K12_IMAGE_TASK_SCHEMA)['$defs']['problemSourceProgress']['properties']['status']['enum'][number]
export interface K12ImageTaskProblemSourceProgressWire {
  problem_id: string
  status: K12ImageTaskProblemSourceStatus
  input_revision: number
  published_revision: number
  current_disposition: 'current'
  page_asset_id?: string
  source_width?: number
  source_height?: number
  source_region?: { x: number; y: number; width: number; height: number } | null
}
export interface K12ImageTaskProblemSourceCoverageWire {
  total: number
  published: number
  skipped: number
  awaiting: number
  failed: number
  status: 'empty' | 'in_progress' | 'complete'
  projection_revision: number
}
export interface K12ImageTaskProblemSourceProgressiveSnapshotWire {
  structure_version: number
  snapshot_revision: number
  problem_progress: K12ImageTaskProblemSourceProgressWire[]
  coverage: K12ImageTaskProblemSourceCoverageWire
}
export interface K12ImageTaskProblemSourceActionResponse {
  command_receipt_id: string
  dispatch_id: string
  problem_id: string
  action: K12ImageTaskProblemSourceAction
  structure_version: number
  input_revision: number
  progressive_snapshot: K12ImageTaskProblemSourceProgressiveSnapshotWire
}

type JsonSchema = Record<string, unknown>

function fail(path: string, expected: string): never {
  throw new Error(` + "`" + `Invalid K12 ImageTask contract at ${path}: expected ${expected}` + "`" + `)
}

function resolveRef(root: JsonSchema, ref: string): JsonSchema {
  if (!ref.startsWith('#/')) fail('$ref', 'local schema reference')
  let current: unknown = root
  for (const token of ref.slice(2).split('/')) {
    current = (current as JsonSchema)[token.replace(/~1/g, '/').replace(/~0/g, '~')]
  }
  if (!current || typeof current !== 'object') fail('$ref', ref)
  return current as JsonSchema
}

function matchesType(value: unknown, type: string): boolean {
  if (type === 'null') return value === null
  if (type === 'array') return Array.isArray(value)
  if (type === 'object') return value !== null && typeof value === 'object' && !Array.isArray(value)
  if (type === 'integer') return typeof value === 'number' && Number.isInteger(value)
  return typeof value === type
}

function validate(root: JsonSchema, schema: JsonSchema, value: unknown, path: string): void {
  if (typeof schema.$ref === 'string') return validate(root, resolveRef(root, schema.$ref), value, path)
  if (Array.isArray(schema.oneOf)) {
    const successes = schema.oneOf.filter((candidate) => {
      try { validate(root, candidate as JsonSchema, value, path); return true } catch { return false }
    })
    if (successes.length !== 1) fail(path, 'exactly one schema variant')
    return
  }
  const types = Array.isArray(schema.type) ? schema.type : [schema.type]
  if (types[0] !== undefined && !types.some((type) => typeof type === 'string' && matchesType(value, type))) {
    fail(path, types.join('|'))
  }
  if (typeof value === 'string' && typeof schema.minLength === 'number' && value.length < schema.minLength) fail(path, 'non-empty string')
  if (Array.isArray(schema.enum) && !schema.enum.includes(value)) fail(path, 'enum member')
  if ('const' in schema && !Object.is(value, schema.const)) fail(path, 'constant value')
  if (typeof value === 'number' && typeof schema.minimum === 'number' && value < schema.minimum) fail(path, ` + "`" + `number >= ${schema.minimum}` + "`" + `)
  if (Array.isArray(value) && schema.items && typeof schema.items === 'object') {
    value.forEach((item, index) => validate(root, schema.items as JsonSchema, item, ` + "`" + `${path}[${index}]` + "`" + `))
  }
  if (value !== null && typeof value === 'object' && !Array.isArray(value)) {
    const record = value as Record<string, unknown>
    const properties = (schema.properties ?? {}) as Record<string, JsonSchema>
    for (const required of (schema.required ?? []) as string[]) {
      if (!(required in record)) fail(` + "`" + `${path}.${required}` + "`" + `, 'required property')
    }
    if (schema.additionalProperties === false) {
      for (const key of Object.keys(record)) if (!(key in properties)) fail(` + "`" + `${path}.${key}` + "`" + `, 'declared property')
    }
    for (const [key, child] of Object.entries(properties)) {
      if (key in record) validate(root, child, record[key], ` + "`" + `${path}.${key}` + "`" + `)
    }
  }
}

function assertDefinition(name: string, value: unknown): void {
  const root = K12_IMAGE_TASK_SCHEMA as unknown as JsonSchema
  validate(root, resolveRef(root, ` + "`" + `#/$defs/${name}` + "`" + `), value, '$')
}

export function assertK12ImageTaskCreateResponse(value: unknown): asserts value is K12ImageTaskCreateResponse { assertDefinition('createResponse', value) }
export function assertK12ImageTaskDispatchResponse(value: unknown): asserts value is K12ImageTaskDispatchResponse { assertDefinition('dispatchResponse', value) }
export function assertK12ImageTaskResultResponse(value: unknown): asserts value is K12ImageTaskResultResponse { assertDefinition('resultResponse', value) }
export function assertK12ImageTaskProblemSourceActionResponse(value: unknown): asserts value is K12ImageTaskProblemSourceActionResponse {
  assertDefinition('problemSourceActionResponse', value)
}
export function validateImageTaskCreate(value: unknown): boolean {
  try { assertK12ImageTaskCreateResponse(value); return true } catch { return false }
}
export function validateImageTaskDispatch(value: unknown): boolean {
  try { assertK12ImageTaskDispatchResponse(value); return true } catch { return false }
}
export function validateImageTaskResult(value: unknown): boolean {
  try { assertK12ImageTaskResultResponse(value); return true } catch { return false }
}
export function validateImageTaskSourceAction(value: unknown): boolean {
  try { assertK12ImageTaskProblemSourceActionResponse(value); return true } catch { return false }
}
`)
}
